-- Countries Table
INSERT INTO final_project.countries (country_name) VALUES
('Indonesia'),
('Jordan'),
('Mongolia'),
('United Kingdom'),
('Paraguay'),
('Romania'),
('Belgium'),
('Honduras'),
('Lebanon'),
('Peru'),
('Mexico'),
('Kyrgyzstan'),
('Bulgaria'),
('Albania'),
('Canada'),
('Mauritius'),
('Nigeria'),
('Chile'),
('Croatia'),
('Madagascar'),
('Philippines'),
('Malta'),
('China'),
('Russia'),
('New Zealand'),
('Uganda'),
('Democratic Republic of the Congo'),
('Iran'),
('Botswana'),
('Costa Rica'),
('Estonia'),
('Sri Lanka'),
('Mozambique'),
('Ghana'),
('Uruguay'),
('Malaysia'),
('Cameroon'),
('Dominican Republic'),
('Pakistan'),
('Latvia'),
('Niger'),
('Iraq'),
('Thailand'),
('Lithuania'),
('Sudan'),
('Nepal'),
('Georgia'),
('Azerbaijan'),
('Czech Republic'),
('Nicaragua'),
('Argentina'),
('France'),
('Ukraine'),
('Mali'),
('Germany'),
('Hungary'),
('Syria'),
('Zambia'),
('Colombia'),
('Sierra Leone'),
('Slovenia'),
('Spain'),
('Moldova'),
('East Timor'),
('Malawi'),
('Kenya'),
('Portugal'),
('Vietnam'),
('Burkina Faso'),
('Tanzania'),
('Israel'),
('Poland'),
('Benin'),
('Turkey'),
('Brazil'),
('Armenia'),
('Fiji'),
('Serbia'),
('Togo'),
('Barbados'),
('Oman'),
('Morocco'),
('Trinidad and Tobago'),
('Luxembourg'),
('Bangladesh'),
('Australia'),
('Ivory Coast'),
('Senegal'),
('Kuwait'),
('Myanmar'),
('Tajikistan'),
('Kazakhstan'),
('Cape Verde'),
('Afghanistan'),
('Tunisia'),
('Laos'),
('Guatemala'),
('Saudi Arabia'),
('Jamaica'),
('Algeria'),
('Slovakia'),
('Greece'),
('India'),
('The Gambia'),
('Belize'),
('South Korea'),
('United States'),
('Papua New Guinea'),
('Gabon'),
('Angola');

-- Cities Table
INSERT INTO cities (id, city_name, city_type) VALUES
(1, 'Kabul', 'capital'),
(1, 'Kabul', 'largest'),
(2, 'Tirana', 'capital'),
(2, 'Tirana', 'largest'),
(3, 'Algiers', 'capital'),
(3, 'Algiers', 'largest'),
(4, 'Luanda', 'capital'),
(4, 'Luanda', 'largest'),
(5, 'Buenos Aires', 'capital'),
(5, 'Buenos Aires', 'largest'),
(6, 'Yerevan', 'capital'),
(6, 'Yerevan', 'largest'),
(7, 'Canberra', 'capital'),
(7, 'Sydney', 'largest'),
(8, 'Baku', 'capital'),
(8, 'Baku', 'largest'),
(9, 'Dhaka', 'capital'),
(9, 'Dhaka', 'largest'),
(10, 'Bridgetown', 'capital'),
(10, 'Bridgetown', 'largest'),
(11, 'City of Brussels', 'capital'),
(11, 'Brussels', 'largest'),
(12, 'Belmopan', 'capital'),
(12, 'Belize City', 'largest'),
(13, 'Porto-Novo', 'capital'),
(13, 'Cotonou', 'largest'),
(14, 'Gaborone', 'capital'),
(14, 'Gaborone', 'largest'),
(15, 'Bras   ', 'capital'),
(15, 'S    ', 'largest'),
(16, 'Sofia', 'capital'),
(16, 'Sofia', 'largest'),
(17, 'Ouagadougou', 'capital'),
(17, 'Ouagadougou', 'largest'),
(18, 'Yamoussoukro', 'capital'),
(18, 'Abidjan', 'largest'),
(19, 'Praia', 'capital'),
(19, 'Praia', 'largest'),
(20, 'Yaound ', 'capital'),
(20, 'Douala', 'largest'),
(21, 'Ottawa', 'capital'),
(21, 'Toronto', 'largest'),
(22, 'Santiago', 'capital'),
(22, 'Santiago', 'largest'),
(23, 'Beijing', 'capital'),
(23, 'Shanghai', 'largest'),
(24, 'Bogot ', 'capital'),
(24, 'Bogot ', 'largest'),
(25, 'San Jos      ', 'capital'),
(25, 'San Jos      ', 'largest'),
(26, 'Zagreb', 'capital'),
(26, 'Zagreb', 'largest'),
(27, 'Prague', 'capital'),
(27, 'Prague', 'largest'),
(28, 'Kinshasa', 'capital'),
(28, 'Kinshasa', 'largest'),
(29, 'Santo Domingo', 'capital'),
(29, 'Santo Domingo', 'largest'),
(30, 'Tallinn', 'capital'),
(30, 'Tallinn', 'largest'),
(31, 'Suva', 'capital'),
(31, 'Suva', 'largest'),
(32, 'Paris', 'capital'),
(32, 'Paris', 'largest'),
(33, 'Libreville', 'capital'),
(33, 'Libreville', 'largest'),
(34, 'Banjul', 'capital'),
(34, 'Serekunda', 'largest'),
(35, 'Tbilisi', 'capital'),
(35, 'Tbilisi', 'largest'),
(36, 'Berlin', 'capital'),
(36, 'Berlin', 'largest'),
(37, 'Accra', 'capital'),
(37, 'Accra', 'largest'),
(38, 'Athens', 'capital'),
(38, 'Macedonia', 'largest'),
(39, 'Guatemala City', 'capital'),
(39, 'Guatemala City', 'largest'),
(40, 'Tegucigalpa', 'capital'),
(40, 'Tegucigalpa', 'largest'),
(41, 'Budapest', 'capital'),
(41, 'Budapest', 'largest'),
(42, 'New Delhi', 'capital'),
(42, 'Kurebhar', 'largest'),
(43, 'Jakarta', 'capital'),
(43, 'Kalimantan', 'largest'),
(44, 'Tehran', 'capital'),
(44, 'Tehran', 'largest'),
(45, 'Baghdad', 'capital'),
(45, 'Baghdad', 'largest'),
(46, 'Jerusalem', 'capital'),
(46, 'Jerusalem', 'largest'),
(47, 'Kingston Jamaica', 'capital'),
(47, 'Kingston Jamaica', 'largest'),
(48, 'Amman', 'capital'),
(48, 'Amman', 'largest'),
(49, 'Astana', 'capital'),
(49, 'Almaty', 'largest'),
(50, 'Nairobi', 'capital'),
(50, 'Nairobi', 'largest'),
(51, 'Kuwait City', 'capital'),
(51, 'Kuwait City', 'largest'),
(52, 'Bishkek', 'capital'),
(52, 'Bishkek', 'largest'),
(53, 'Vientiane', 'capital'),
(53, 'Vientiane', 'largest'),
(54, 'Riga', 'capital'),
(54, 'Riga', 'largest'),
(55, 'Beirut', 'capital'),
(55, 'Tripoli Lebanon', 'largest'),
(56, 'Vilnius', 'capital'),
(56, 'Vilnius', 'largest'),
(57, 'Luxembourg City', 'capital'),
(57, 'Luxembourg City', 'largest'),
(58, 'Antananarivo', 'capital'),
(58, 'Antananarivo', 'largest'),
(59, 'Lilongwe', 'capital'),
(59, 'Lilongwe', 'largest'),
(60, 'Kuala Lumpur', 'capital'),
(60, 'Johor Bahru', 'largest'),
(61, 'Bamako', 'capital'),
(61, 'Bamako', 'largest'),
(62, 'Valletta', 'capital'),
(62, 'Birkirkara', 'largest'),
(63, 'Port Louis', 'capital'),
(63, 'Port Louis', 'largest'),
(64, 'Mexico City', 'capital'),
(64, 'Mexico City', 'largest'),
(65, 'Chi    ', 'capital'),
(65, 'Chi    ', 'largest'),
(66, 'Ulaanbaatar', 'capital'),
(66, 'Ulaanbaatar', 'largest'),
(67, 'Rabat', 'capital'),
(67, 'Casablanca', 'largest'),
(68, 'Maputo', 'capital'),
(68, 'Maputo', 'largest'),
(69, 'Naypyidaw', 'capital'),
(69, 'Yangon', 'largest'),
(70, 'Kathmandu', 'capital'),
(70, 'Kathmandu', 'largest'),
(71, 'Wellington', 'capital'),
(71, 'Auckland', 'largest'),
(72, 'Managua', 'capital'),
(72, 'Managua', 'largest'),
(73, 'Niamey', 'capital'),
(73, 'Niamey', 'largest'),
(74, 'Abuja', 'capital'),
(74, 'Lagos', 'largest'),
(75, 'Muscat', 'capital'),
(75, 'Seeb', 'largest'),
(76, 'Islamabad', 'capital'),
(76, 'Karachi', 'largest'),
(77, 'Port Moresby', 'capital'),
(77, 'Port Moresby', 'largest'),
(78, 'Asunci  ', 'capital'),
(78, 'Ciudad del Este', 'largest'),
(79, 'Lima', 'capital'),
(79, 'Lima', 'largest'),
(80, 'Manila', 'capital'),
(80, 'Manila', 'largest'),
(81, 'Warsaw', 'capital'),
(81, 'Warsaw', 'largest'),
(82, 'Lisbon', 'capital'),
(82, 'Lisbon', 'largest'),
(83, 'Bucharest', 'capital'),
(83, 'Bucharest', 'largest'),
(84, 'Moscow', 'capital'),
(84, 'Moscow', 'largest'),
(85, 'Riyadh', 'capital'),
(85, 'Riyadh', 'largest'),
(86, 'Dakar', 'capital'),
(86, 'Pikine', 'largest'),
(87, 'Belgrade', 'capital'),
(87, 'Belgrade', 'largest'),
(88, 'Freetown', 'capital'),
(88, 'Freetown', 'largest'),
(89, 'Bratislava', 'capital'),
(89, 'Bratislava', 'largest'),
(90, 'Ljubljana', 'capital'),
(90, 'Ljubljana', 'largest'),
(91, 'Seoul', 'capital'),
(91, 'Seoul', 'largest'),
(92, 'Madrid', 'capital'),
(92, 'Madrid', 'largest'),
(93, 'Colombo', 'capital'),
(93, 'Colombo', 'largest'),
(94, 'Khartoum', 'capital'),
(94, 'Omdurman', 'largest'),
(95, 'Damascus', 'capital'),
(95, 'Damascus', 'largest'),
(96, 'Dushanbe', 'capital'),
(96, 'Dushanbe', 'largest'),
(97, 'Dodoma', 'capital'),
(97, 'Dar es Salaam', 'largest'),
(98, 'Bangkok', 'capital'),
(98, 'Bangkok', 'largest'),
(99, 'Dili', 'capital'),
(99, 'Dili', 'largest'),
(100, 'Lom ', 'capital'),
(100, 'Lom ', 'largest'),
(101, 'Port of Spain', 'capital'),
(101, 'Chaguanas', 'largest'),
(102, 'Tunis', 'capital'),
(102, 'Tunis', 'largest'),
(103, 'Ankara', 'capital'),
(103, 'Istanbul', 'largest'),
(104, 'Kampala', 'capital'),
(104, 'Buganda', 'largest'),
(105, 'Kyiv', 'capital'),
(105, 'Kyiv', 'largest'),
(106, 'London', 'capital'),
(106, 'London', 'largest'),
(107, 'Washington D.C.', 'capital'),
(107, 'New York City', 'largest'),
(108, 'Montevideo', 'capital'),
(108, 'Montevideo', 'largest'),
(109, 'Hanoi', 'capital'),
(109, 'Ho Chi Minh City', 'largest'),
(110, 'Lusaka', 'capital'),
(110, 'Lusaka', 'largest');

-- Happiness Table:
